name: Test CLI Version

on:
  push:

env:
  DEVHUB_ALIAS:                     "devhub"
  CLI_VERSION:                      ${{ vars.SFDX_CLI_VERSION }}

jobs:
 
  Install_SFDX_CLI_and_Create_Scratch_Org:
    runs-on: ubuntu-latest

    steps:

        - name: INSTALL SFDX CLI
          shell: pwsh
          run: |
            ls -R

        - name: AUTHENTICATE DEVHUB AUTH URL
          env:
            DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
          shell: pwsh
          run: . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"
    
        - name: CREATE SCRATCH ORG
          shell: pwsh
          run: . ./ci_system/sfdx/create_scratch_org.ps1 -devhub_alias $env:DEVHUB_ALIAS -scratch_org_alias $env:SCRATCH_ORG_ALIAS
    