name: Test CLI Version

on:
  push:
  workflow_dispatch:

env:
  DEVHUB_ALIAS:                     "devhub"
  CLI_VERSION:                      ${{ vars.SFDX_CLI_VERSION }}

jobs:
 
  Install_SFDX_CLI_and_Create_Scratch_Org:
    runs-on: ${{ vars.GH_ACTIONS_OPERATING_SYSTEM }}

    steps:
        - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
          uses: actions/checkout@v3

        - name: INSTALL SFDX CLI
          shell: pwsh
          run: |
            . .\ci_system\sfdx\install-sfdx.ps1 -cli_version "$env:CLI_VERSION"  

        - name: AUTHENTICATE DEVHUB AUTH URL
          env:
            DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
          shell: pwsh
          run: . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"
    
        - name: CREATE SCRATCH ORG
          shell: pwsh
          run: . ./ci_system/sfdx/sfdx_create_scratch_org.ps1 -devhub_alias $env:DEVHUB_ALIAS -scratch_org_alias "scratch-test"
    
  SF_COMMAND_Install_SFDX_CLI_and_Create_Scratch_Org:
    
    runs-on: ubuntu-latest

    steps:

        # - name: NODE INSTALL OVERWRITE FOR ISSUE https://github.com/forcedotcom/cli/issues/2125
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: '18.14.2'

        - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
          uses: actions/checkout@v3

        - name: INSTALL SFDX CLI
          shell: pwsh
          run: |
            . .\ci_system\sfdx\install-sfdx.ps1 -cli_version "$env:CLI_VERSION"  

        - name: AUTHENTICATE DEVHUB AUTH URL
          env:
              DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
          shell: pwsh
          run: . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"

        - name: CREATE SCRATCH ORG
          shell: pwsh
          run: . ./ci_system/sfdx/sf_create_scratch_org.ps1 -devhub_alias $env:DEVHUB_ALIAS -scratch_org_alias "scratch-test"

  Package_Version_Create:

    runs-on: ubuntu-latest

    steps:

        # - name: NODE INSTALL OVERWRITE FOR ISSUE https://github.com/forcedotcom/cli/issues/2125
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: '18.14.2'

        - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
          uses: actions/checkout@v3

        - name: INSTALL SFDX CLI
          shell: pwsh
          run: |
            . .\ci_system\sfdx\install-sfdx.ps1 -cli_version "$env:CLI_VERSION"  

        - name: AUTHENTICATE DEVHUB AUTH URL
          env:
              DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
          shell: pwsh
          run: |
            Write-Host "runner context :${{ runner.temp }} "
            . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"

        - name: CREATE PACKAGE VERSION
          shell: pwsh
          run: . ./ci_system/sfdx/package/sf_create_package_version.ps1 -devhub_alias $env:DEVHUB_ALIAS -package_alias "dx-cli-testing"


  full-package-validation-post-merge-workflow-completion:
      
    runs-on: ${{ vars.GH_ACTIONS_OPERATING_SYSTEM }}
    
   
    steps:

      - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
        uses: actions/checkout@v3

      - name: INSTALL SFDX CLI
        shell: pwsh
        run: |
          . .\ci_system\sfdx\install-sfdx.ps1 -cli_version "$env:CLI_VERSION"  

      - name: AUTHENTICATE DEVHUB AUTH URL
        env:
            DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
        shell: pwsh
        run: |
          Write-Host "runner context :${{ runner.temp }} "
          . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"

      - name: CREATE PACKAGE VERSION
        shell: pwsh
        run: . ./ci_system/sfdx/package/sf_create_package_version.ps1 -devhub_alias $env:DEVHUB_ALIAS -package_alias "dx-cli-testing" 

      - name: SAVE TEMP ARTIFACT
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: SF_LOGS_RESULT
          path: ${{ runner.temp }}

  create-scratch:
    runs-on: ${{ vars.GH_ACTIONS_OPERATING_SYSTEM }}

    env:
      DTC_RELEASE_CICD_KEY_BASE64:  ${{ secrets.DTC_RELEASE_CICD_KEY_BASE64 }}
      DEVHUB_ALIAS:                 "devhub"
      SF_DEVHUB_CLIENTID:           ${{ secrets.SF_DEVHUB_CLIENTID }}
      SF_DEVHUB_KEY_BASE64:         ${{ secrets.SF_DEVHUB_KEY_BASE64 }}
      SF_DEVHUB_ORG_URL:            ${{ secrets.SF_DEVHUB_ORG_URL }}
      DEVHUB_ORG_USERNAME:          ${{ secrets.DEVHUB_ORG_USERNAME }}
      SCRATCH_ORG_ALIAS:            "ci-scratch-org"

    steps:

      - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
        uses: actions/checkout@v3

      - name: INSTALL SALESFORCE CLI TAR AND SET SALESFORCE CLI ALIASES
        shell: pwsh
        run: |
          . ./ci-cd/install/install_tar_windows_salesforce_cli.ps1
        
      - name: AUTHENTICATE DEVHUB PWSH JWT
        shell: pwsh
        run: . .\ci-cd\authenticate\authenticate-salesforce-devhub.ps1 -auth_key_base64 $env:SF_DEVHUB_KEY_BASE64 -auth_clientid $env:SF_DEVHUB_CLIENTID -auth_username $env:DEVHUB_ORG_USERNAME -auth_org_url $env:SF_DEVHUB_ORG_URL -devhub_alias $env:DEVHUB_ALIAS
    
      # - name: AUTHENTICATE DEVHUB ORG
      #   shell: pwsh
      #   run: . .\ci-cd\authenticate\authenticate-salesforce-authurl.ps1 -org_alias $env:DEVHUB_ALIAS -auth_url $env:DEVHUB_AUTH_URL

      - name: CREATE SCRATCH ORG
        shell: pwsh
        run: |
          sfdx force:org:create --targetdevhubusername devhub --definitionfile config/project-scratch-def.json --setalias $env:SCRATCH_ORG_ALIAS --durationdays 1 --setdefaultusername --loglevel trace
