name: Salesforce Package Version Installation Failure on Org with Existing Package Version

on:
  push:
  workflow_dispatch:

env:
  DEVHUB_ALIAS:                     "devhub"
  CLI_VERSION:                      ${{ vars.SFDX_CLI_VERSION }}
  PACKAGE_NAME:                     ${{ vars.PACKAGE_NAME }}
  SF_DEVHUB_CLIENTID:               ${{ secrets.SF_DEVHUB_CLIENTID }}
  SF_DEVHUB_KEY_BASE64:             ${{ secrets.SF_DEVHUB_KEY_BASE64 }}
  SF_DEVHUB_ORG_URL:                ${{ secrets.SF_DEVHUB_ORG_URL }}
  DEVHUB_ORG_USERNAME:              ${{ secrets.DEVHUB_ORG_USERNAME }}
  SCRATCH_ALIAS:                    "ci-scratch-org"

jobs:
 
  CREATE-PACKAGE-VERSION-INSTALL-NEW-PACKAGE-VERSION-AND-RETRY:
    
    runs-on: ubuntu-latest

    outputs:
      subscriber_package_version_id: ${{ steps.create_package_version.outputs.subscriber_package_version_id }}
      second_subscriber_package_version_id: ${{ steps.second_create_package_version.outputs.second_subscriber_package_version_id }}


    steps:

        - name: CHECKOUT CURRENT REPOSITORY IN VIRTUAL MACHINE
          uses: actions/checkout@v3

        - name: INSTALL SFDX CLI
          shell: pwsh
          run: |
            . .\ci_system\sfdx\install-sfdx.ps1 -cli_version "$env:CLI_VERSION"  

        - name: AUTHENTICATE DEVHUB AUTH URL
          env:
              DEVHUB_AUTH_URL: ${{ secrets.DEVHUB_AUTH_URL }}
          shell: pwsh
          run: . ./ci_system/sfdx/auth_url.ps1 -auth_url $env:DEVHUB_AUTH_URL -org_alias "$env:DEVHUB_ALIAS"

        - name: CREATE SCRATCH ORG
          shell: pwsh
          run: |
            $Env:SF_LOG_LEVEL = "fatal"
            . ./ci_system/sfdx/sf_create_scratch_org.ps1 -devhub_alias $env:DEVHUB_ALIAS -scratch_org_alias $env:SCRATCH_ALIAS
        
        - name: CREATE SKIP VALIDATION PACKAGE VERSION
          id: create_package_version
          shell: pwsh
          run: |
            $package_name = $env:PACKAGE_NAME
            $subscriber_package_version_id = $( . .\ci_system\sfdx\package\simple_package_version_creation.ps1 -validation_type "skip" `
                                                              -devhub_alias $env:DEVHUB_ALIAS `
                                                              -package_name $package_name )
            "subscriber_package_version_id=$subscriber_package_version_id" >> $env:GITHUB_OUTPUT

        - name: PACKAGE INSTALL TO SCRATCH ORG
          shell: pwsh
          run: |
              echo "This is the suscriber id:"
              $subscriber_package_version_id = '${{ steps.create_package_version.outputs.subscriber_package_version_id }}'
              echo "$subscriber_package_version_id"
              . .\ci_system\sfdx\install_package_version_to_org.ps1 -org_to_install_alias $env:SCRATCH_ALIAS -subscriber_package_version_id $subscriber_package_version_id

        - name: UPDATE TITLE FIELD
          shell: pwsh
          run: |
              $title_field = Get-Content -Raw .\sfdx-source\trouble\objects\Broker__c\fields\Title__c.field-meta.xml
              $upper_limit_random_number = 30 
              $random_number = Get-Random -Minimum 1 -Maximum $upper_limit_random_number
              $title_field -replace "<length>30</length>", "<length>$random_number</length>"
              $title_field = $title_field -replace "<length>30</length>", "<length>22</length>"
              Set-Content .\sfdx-source\trouble\objects\Broker__c\fields\Title__c.field-meta.xml -Value $title_field

        - name: CREATE SECOND SKIP VALIDATION PACKAGE VERSION
          id: second_create_package_version
          shell: pwsh
          run: |
            $package_name = $env:PACKAGE_NAME
            $subscriber_package_version_id = $( . .\ci_system\sfdx\package\simple_package_version_creation.ps1 -validation_type "skip" `
                                                              -devhub_alias $env:DEVHUB_ALIAS `
                                                              -package_name $package_name )
            "second_subscriber_package_version_id=$second_subscriber_package_version_id" >> $env:GITHUB_OUTPUT

        - name: SECOND PACKAGE INSTALL TO SCRATCH ORG
          shell: pwsh
          run: |
              echo "This is the suscriber id:"
              $second_subscriber_package_version_id = '${{ steps.second_create_package_version.outputs.second_subscriber_package_version_id }}'
              echo "$subscriber_package_version_id"
              . .\ci_system\sfdx\install_package_version_to_org.ps1 -org_to_install_alias $env:SCRATCH_ALIAS -subscriber_package_version_id $second_subscriber_package_version_id


